name: Students API Pipeline
on:
  push:
    branches: 
    - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
        env:
          NODE_ENV: development
          PORT: 5000
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: development
          PORT: 5000
      - name: List files
        run: ls dist