name: Students API Pipeline
on:
  push:
    branches: 
    - main
env:
  NODE_ENV: development
  PORT: 5000
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run build
      - name: List files
        run: ls dist